# Generated by Django 5.2.14 on 2026-07-20 23:42

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_backfill_is_system_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='avatar_url',
        ),
        migrations.RemoveField(
            model_name='user',
            name='avatar_url',
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='avatar',
            field=models.TextField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, storage=accounts.models.avatar_storage, upload_to='avatars/'),
        ),
    ]
