# Generated by Django 5.2.14 on 2026-07-22 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('invitation', 'Invitation'), ('mention', 'Mention'), ('page_updated', 'Page modifiée'), ('workflow_stage', 'Changement de workflow'), ('comment', 'Commentaire')], max_length=20),
        ),
    ]
