import type { CSSProperties } from "react";
import {
  AlignCenter,
  AlignLeft,
  AlignRight,
  AtSign,
  Bell,
  Blocks,
  Bold,
  BookOpen,
  Check,
  ChevronDown,
  ChevronRight,
  CircleAlert,
  CircleHelp,
  Clock,
  Code,
  Copy,
  Download,
  ExternalLink,
  FilePlus2,
  FileText,
  GraduationCap,
  Heading,
  History,
  House,
  Info,
  Italic,
  KeyRound,
  LayoutTemplate,
  Link2,
  List,
  Lock,
  LogOut,
  Mail,
  MessageSquare,
  Monitor,
  Moon,
  Pencil,
  Plus,
  Quote,
  RefreshCw,
  Save,
  Scale,
  Search,
  Settings,
  ShieldCheck,
  Siren,
  SquareCheckBig,
  Strikethrough,
  Sun,
  Table,
  Terminal,
  Trash2,
  TriangleAlert,
  Upload,
  User,
  Users,
  Wifi,
  WifiOff,
  Workflow,
  X,
  type LucideIcon,
} from "lucide-react";

/**
 * Single icon vocabulary for the app, backed by lucide-react. Call sites use a
 * stable semantic name (`"trash"`, `"diagram"`) rather than importing lucide
 * directly, so an icon can be swapped in one place — and `IconName` keeps typos
 * from silently rendering a blank square.
 *
 * Stroke width, colour and line joins come from `svg.ic` in index.css so every
 * icon matches the design system at any size.
 */
const ICONS = {
  alert: TriangleAlert,
  alertCircle: CircleAlert,
  alignCenter: AlignCenter,
  alignLeft: AlignLeft,
  alignRight: AlignRight,
  at: AtSign,
  bell: Bell,
  bold: Bold,
  book: BookOpen,
  check: Check,
  checkSquare: SquareCheckBig,
  chevronDown: ChevronDown,
  chevronRight: ChevronRight,
  clock: Clock,
  code: Code,
  comment: MessageSquare,
  copy: Copy,
  diagram: Workflow,
  download: Download,
  externalLink: ExternalLink,
  file: FileText,
  filePlus: FilePlus2,
  graduationCap: GraduationCap,
  heading: Heading,
  help: CircleHelp,
  history: History,
  home: House,
  info: Info,
  italic: Italic,
  key: KeyRound,
  link: Link2,
  list: List,
  lock: Lock,
  logout: LogOut,
  mail: Mail,
  monitor: Monitor,
  moon: Moon,
  pencil: Pencil,
  plus: Plus,
  quote: Quote,
  refresh: RefreshCw,
  save: Save,
  scale: Scale,
  search: Search,
  settings: Settings,
  shield: ShieldCheck,
  siren: Siren,
  strike: Strikethrough,
  sun: Sun,
  table: Table,
  template: LayoutTemplate,
  terminal: Terminal,
  transclude: Blocks,
  trash: Trash2,
  upload: Upload,
  user: User,
  users: Users,
  wifi: Wifi,
  wifiOff: WifiOff,
  x: X,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

interface Props {
  name: IconName;
  size?: number;
  className?: string;
  style?: CSSProperties;
}

export function Icon({ name, size = 14, className = "ic", style }: Props) {
  const Glyph = ICONS[name];
  return <Glyph className={className} size={size} style={style} aria-hidden="true" />;
}
