# Generated by Django 5.2.14 on 2026-07-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteconfig', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_enabled',
            field=models.BooleanField(default=False, help_text="Activer l'envoi d'e-mails via la configuration ci-dessous (sinon fallback sur les variables d'environnement)."),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_from',
            field=models.EmailField(blank=True, default='', help_text="Adresse d'expéditeur. Vide → DEFAULT_FROM_EMAIL de l'environnement.", max_length=254),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host_password',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_host_user',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_port',
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_use_ssl',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
